### ISSUE TITLE
Flake8 error message in the AI Platform Notebook

### ISSUE THREAD

**Issue by Xenopaia** [tarrade/proj_multilingual_text_classification#2]
![image](https://user-images.githubusercontent.com/37111236/76878997-e9ba8980-6875-11ea-9b81-132e69210ade.png)

This error popup occurred several times during a 1 hour time window today.

Applied fixes:
- pip install flake8
- conda install flake8
- restart the vm
- restart the kernel
- disabled jupyterlab-flake8 in the jupyter-notebook env

**Comment by tarrade** [comment]
this jupyter lab extension was commented out since created too much problem

**Comment by tarrade** [comment]
closing since the extension was removed and it exist a ticket on the github from Flake8 and on the on on custom ai platform notebook
