### ISSUE TITLE
Find imdb-like movie review datasets in FR, DE and IT

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_multilingual_text_classification#22]

**Comment by Xenopaia** [comment]
There might not be any available datasets in French and German for IMDb reviews.

Alternatives for us to use may be:
- Amazon product reviews in EN, DE, FR (and JP): https://webis.de/data/webis-cls-10.html
Training and testing sets contain 2'000 documents each (labelled positive/negative). Download: https://zenodo.org/record/3251672
The data was crawled by a research team in 2009. Paper: https://webis.de/downloads/publications/papers/stein_2010k.pdf
- MLDoc: Reuters corpus, RCV2: https://trec.nist.gov/data/reuters/reuters.html
13 languages (including EN, DE, FR, IT), over 487'000 news stories
We would need to take a sample of this big dataset.
Facebook's repo for the retrieval: https://github.com/facebookresearch/MLDoc

**Comment by tarrade** [comment]
I agree, the only think I found https://github.com/tchambon/deepfrench said "The movie reviews have been downloaded from a french imdb-like website and include 11K positives reviews, 11K negatives reviews as well as 51K unlabeled reviews for language model tuning" but these data are not public

**Comment by tarrade** [comment]
we didn't find any dataset ready to use so the only solution left so the solution was to use GCP Translate API to translate documents but thi is quite expensive: 20 CF per 1 million of character !

Some dataset collected by a Zurich company: tweet in German with 4 sentiments (positive, negative, mixed and unknow)
https://www.spinningbytes.com/resources/germansentiment/
