### ISSUE TITLE
How to choose the batch size for training and validation datasets?

### ISSUE THREAD

**Issue by Xenopaia** [tarrade/proj_multilingual_text_classification#3]
Batch sizes vary a lot between models. Also, there are sometimes differences in the batch sizes of training and validation.

How sensible are batches of 32 compared to 500?

Reference: https://blog.tensorflow.org/2019/11/hugging-face-state-of-art-natural.html

**Comment by tarrade** [comment]
could be set as an hyper-parameter. Google did quite some research on this topic and it is summarized below and driven by out of memory contrained:
https://github.com/google-research/bert#out-of-memory-issues
