### ISSUE TITLE
What entails fine-tuning in NLP transfer learning?

### ISSUE THREAD

**Issue by Xenopaia** [tarrade/proj_multilingual_text_classification#4]
What options are there for fine-tuning BERT models?

How can we implement freezing different layers of the model?

**Comment by tarrade** [comment]
Nice studies:
https://github.com/uzaymacar/comparatively-finetuning-bert

and the answer:
https://github.com/huggingface/transformers/issues/587
"When BERT is fine-tuned, all layers are trained "

this is different from transfer learning where only the few last layer are retrained!
