### ISSUE TITLE
Preprocessing: How to Deal with Text Truncation

### ISSUE THREAD

**Issue by vluechinger** [tarrade/proj_multilingual_text_classification#56]
At the moment, we just took the first 510 tokens of each sequence. 
Other approaches would be to take the last 510 tokens or to do a mix by taking the first 255 and the last 255 tokens. For movie reviews, this could improve the model and is one aspect we could try out.

**Comment by tarrade** [comment]
https://arxiv.org/abs/2004.05150

**Comment by tarrade** [comment]
Important for long text. Here we have 95% of the text with the token size. LongTransformer can be an option.
