### ISSUE TITLE
Further Pre-training: do-able? Useful?

### ISSUE THREAD

**Issue by vluechinger** [tarrade/proj_multilingual_text_classification#58]
Papers like https://arxiv.org/pdf/1910.10683.pdf show that further pre-training BERT on the target domain, on other languages etc. is generally useful under certain circumstances. In general, they state that pre-training + fine-tuning is always better than just fine-tuning and skipping pre-training.

This is something we could implement to improve our approach.

**Comment by tarrade** [comment]
Will take too much time and cost too much for a little impact. To see with other project when we need AXA data and insurance context
