### ISSUE TITLE
How can we plot the model history in steps?

### ISSUE THREAD

**Issue by Xenopaia** [tarrade/proj_multilingual_text_classification#6]
Possible approaches:

- Tensorboard
- using the saved models from each step of the process, implementing the callback option

**Comment by tarrade** [comment]
it seems that Tensorboard is displaying what is provided by Keras.

what is working is to create a callback and store acc and loss per step and reuse some plot function to create the plot. This is implemented in notebook/00-Test/08_SST2_Huggingface_model.ipynb

this is a good solution but we need something in TensorBoard. Opening a separate issue

![image](https://user-images.githubusercontent.com/12021701/77640001-ef8d2a80-6f59-11ea-9233-d486957f33cc.png)
(I need to fix the legend from epoch --> step)
